### ISSUE TITLE
How do I specify arrow directions for my tooltip?

### ISSUE THREAD

**Issue by berenyiaustin** [calmcom/SexyTooltip#7]

**Comment by tsheaff** [comment]
https://github.com/calm/SexyTooltip#arrow-direction

From the README:

## Arrow direction

You can specify an array of `permittedArrowDirections` which specify the preference order of pointing directions.  The tooltip will attempt to fit itself inside the `inView` you passed while maintaining the arrow pointing at the target view or point.  For example, if you're pointing at a view that's moving around the screen, SexyTooltip will continue to be visible as the view moves to the edges by changing its direction in order to stay within the bounds of the `inView`.  This is very powerful for complex tooltip scenarios or cases where you're not sure how the interface might look at the moment of presentation (e.g. variable text sizes)

```objc
typedef NS_ENUM(NSUInteger, SexyTooltipArrowDirection) {
    SexyTooltipArrowDirectionUp,
    SexyTooltipArrowDirectionDown,
    SexyTooltipArrowDirectionLeft,
    SexyTooltipArrowDirectionRight
};
```
